kind: Deployment
apiVersion: apps/v1
metadata:
  name: fortio
spec:
  selector:
    matchLabels:
      app: fortio
  replicas: 1
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - name: fortio
        image: istio/fortio:1.1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http-fortio
          - containerPort: 8079
            name: grpc-ping
      restartPolicy: Always
---
