kind: Deployment
apiVersion: apps/v1
metadata:
  name: fortio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
      version: v1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: fortio
        version: v1
    spec:
      containers:
      - name: fortio
        image: istio/fortio:1.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
      restartPolicy: Always
---
