kind: Deployment
apiVersion: apps/v1
metadata:
  name: coffee-shop
spec:
  selector:
    matchLabels:
      app: coffee-shop
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:quarkus-zero-downtime-1
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl -f localhost:8080/health"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      restartPolicy: Always
---
