context: coffee-shop-k8s.example.com
global:
  subsets: v1
  newVersion: v1
  image: 1
include:
  - name: deployment
    path: coffee-shop/deployment.tpl.yaml
  - name: routing
    path: coffee-shop/routing.tpl.yaml
---
