apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: zero-downtime-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zero-downtime
spec:
  hosts:
  - "*"
  gateways:
  - zero-downtime-gateway
  http:
  - route:
    - destination:
        host: zero-downtime
        port:
          number: 8080
---

# to self
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: zero-downtime
spec:
  hosts:
  - "zero-downtime.example.com"
  addresses:
  - "35.204.120.251"
  - "35.190.25.125"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_EXTERNAL
---
