kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: satellite
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: satellite
        version: v1
    spec:
      containers:
      - name: satellite
        image: istio/fortio
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
