kind: Service
apiVersion: v1
metadata:
  name: zero-downtime
  labels:
    app: zero-downtime
spec:
  selector:
    app: zero-downtime
  ports:
    - port: 8080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: zero-downtime
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zero-downtime
        version: v1
    spec:
      containers:
      - name: zero-downtime
        image: docker.sebastian-daschner.com/zero-downtime:1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /zero-downtime/resources/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "curl localhost:8080/zero-downtime/resources/health -XDELETE && sleep 20"]
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: zero-downtime
#  annotations:
#    kubernetes.io/ingress.class: nginx
spec:
  backend:
    serviceName: zero-downtime
    servicePort: 8080
---
