kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: zero-downtime-{{ .newVersion }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zero-downtime
        version: {{ .newVersion }}
    spec:
      containers:
      - name: zero-downtime
        image: docker.sebastian-daschner.com/zero-downtime:{{ .image }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /zero-downtime/resources/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        ports:
        - containerPort: 8080
#        lifecycle:
#          preStop:
#            exec:
#              command: ["/bin/bash", "-c", "curl localhost:8080/zero-downtime/resources/health -XDELETE && sleep 20"]
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
